//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecipe
    {
        public string RecipeID { get; set; }
        public string RecipeName { get; set; }
        public string RecipeEffect { get; set; }
        public string RecipeType { get; set; }
        public string Recipe_Description { get; set; }
    }
}
